### ISSUE TITLE
 xdk5344 Check the following functions

### ISSUE THREAD

**Issue by jarupxx** [jarupxx/Cxbx-Reloaded#1]
I generated a separate XDK file for 5344, but the following functions have not been confirmed.
- [x] D3DDevice_SetVerticalBlankCallback, 5344
- [x] D3DDevice_SetSwapCallback, 5344
- [x] D3DDevice_SetRenderTargetFast, 5344
https://github.com/jarupxx/Cxbx-Reloaded/commits/xdk5344

**Comment by PatrickvL** [comment]
Your link is wrong; I suspect you mean https://github.com/jarupxx/Cxbx-Reloaded/commits/xdk5344

Before this is merged in, the HLE scanning code needs to be updated so that version aliassing doesn't skip this new database.

**Comment by PatrickvL** [comment]
This comes from the Dxbx patterns :
```
_D3DDevice_SetVerticalBlankCallback@4 5344 d3d8 0020 8B4424048B0D........898188190000C2040090909090909090909090909090 00 0000 ^0006D _D3D__pDevice
_D3DDevice_SetSwapCallback@4 5344 d3d8 0020 8B4424048B0D........898184190000C2040090909090909090909090909090 00 0000 ^0006D _D3D__pDevice
_D3DDevice_SetRenderTargetFast@12 5344 d3d8 0120 558B6C240856578B3D........55E8........8B87E41500008B481485C97402 10 371A .......8B87E815000085C089AFE4150000741B8B481485C974028BC18B4F2C8948088B97E815000052E8........8B373B7704538B5C2418899FE81500007207E8........8BF08B4504C7061002040089460433D23BDAC746081002040089460C7519C746100C030400895614C746182C03040089561C8D4620EB4553E8........8B5B04B814020400894610895E14894618895E1C8B0D........33C085C90F95C0C746200C03040033D2894624A1........C746282C03040089462C8D46308B4F08F6C5015B741D3BAFF4150000751581E1FFFEFFFF894F08C7003001040089500483C00889075F5E5DC20C00 ^0009D _D3D__pDevice ^000FR ?InternalAddRefSurface@D3D@@YGXPAUD3DResource@@@Z ^0030R ?InternalReleaseSurface@D3D@@YGXPAUD3DResource@@@Z ^005BR ?InternalReleaseSurface@D3D@@YGXPAUD3DResource@@@Z ^0072R _D3DDevice_MakeSpace@0 ^00AFR ?InternalAddRefSurface@D3D@@YGXPAUD3DResource@@@Z ^00C9D _D3D__RenderState+023C ^00E1D _D3D__RenderState+0240
```
Did you use those? Then verifying them might not be neccessary.

PS: https://github.com/jarupxx/Cxbx-Reloaded/blob/xdk5344/src/CxbxKrnl/HLEDataBase/D3D8.1.0.5344.h contains `D3DDevice_SetRenderState_CullMode_5233` - shouldn't that be `D3DDevice_SetRenderState_CullMode_5344` instead?

**Comment by jarupxx** [comment]
I checked the Dxbx patterns and moved 3 functions, so remove all 5344 in 5233 database.
Also, I updated the HLE scanning code so use the new 5344 database.

<code>D3DDevice_SetRenderState_CullMode_5233</code> was unnecessary.
This version also use 5233 to detect D3DDeferredRenderState.

PS: Thank you for teaching me how to write a link.

**Comment by jarupxx** [comment]
Quick test with 5344 software, I noticed that many OOVPAs are missing.
Is it better if I add the OOVPAs before make a pull request?

**Comment by jarupxx** [comment]
Let's investigate missing OOVPAs later.
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/208
